ABS ACOS ADD_MONTHS ASCII ASCIISTR ASIN ATAN 
ATAN2 BFILENAME BITAND CARDINALITY CEIL 
CHARTOROWID CHR COALESCE COMMIT COMPOSE CONCAT                         
CONTINUE CONVERT COS COSH CUBE CURRENT_DATE                   
CURRENT_TIME CURRENT_TIMESTAMP DBTIMEZONE                     
DECODE DECOMPOSE DEREF DUMP EMPTY_BLOB 
EMPTY_CLOB EXISTS EXP FLOOR FROM_TZ GLB  
GREATEST GREATEST_LB GROUPING HEXTORAW INITCAP                        
INSTR INSTR2 INSTR4 INSTRB INSTRC ISNCHAR                        
LAST_DAY LEAST LEAST_UB LENGTH LENGTH2 LENGTH4                        
LOCALTIMESTAMP LOG LOWER LPAD LTRIM LUB 
MONTHS_BETWEEN NANVL NCHARTOROWID NCHR NEW_TIME                       
NEXT_DAY NHEXTORAW NLSSORT NLS_CHARSET_DECL_LEN           
NLS_CHARSET_ID NLS_CHARSET_NAME NLS_INITCAP 
LENGTHB LENGTHC LEVEL LN LOCALTIME 
