TO_BINARY_FLOAT TO_BLOB TO_CHAR TO_CLOB TO_DATE                        
TO_DSINTERVAL TO_LABEL TO_MULTI_BYTE TO_NCHAR                       
TO_NCLOB TO_NUMBER TO_RAW TO_SINGLE_BYTE                 
TO_TIME TO_TIMESTAMP TO_TIMESTAMP_TZ TO_TIME_TZ                     
TO_YMINTERVAL TRANSLATE TRIM TRUNC TZ_OFFSET                      
UID UNISTR UPPER UROWID  USER USERENV VALUE                          
VSIZE XOR 
