NLS_LOWER NLS_UPPER NULLFN NULLIF 
NUMTODSINTERVAL NUMTOYMINTERVAL NVL POWER                          
RAWTOHEX RAWTONHEX REF REGEXP_INSTR REGEXP_LIKE                    
REGEXP_REPLACE REGEXP_SUBSTR REMAINDER REPLACE                                            
ROLLUP ROUND ROWID  ROWIDTOCHAR ROWIDTONCHAR                   
ROWLABEL ROWNUM RPAD RTRIM SAVEPOINT 
SESSIONTIMEZONE SET SIGN SIN SINH SOUNDEX                         
SUBSTRB SUBSTRC SYSDATE SYSTIMESTAMP 
SYS_AT_TIME_ZONE SYS_CONTEXT SYS_EXTRACT_UTC                
SYS_GUID SYS_LITERALTODATE 
SYS_LITERALTODSINTERVAL SYS_LITERALTOTIME              
SYS_LITERALTOTIMESTAMP SYS_LITERALTOTZTIME            
SYS_LITERALTOTZTIMESTAMP SYS_LITERALTOYMINTERVAL        
TAN TANH TO_ANYLOB TO_BINARY_DOUBLE
SQLCODE SQLERRM SQRT SUBSTR SUBSTR2 SUBSTR4 
