MONITORING MONTH MOUNT MEMBER MERGE MULTISET
MATERIALIZED NATURAL NATURALN NEW NEXT NEXTVAL
NITRANS NOARCHIVELOG NOAUDIT NOCACHE 
NOCOMPRESS NOCOPY NOCYCLE NOMAXVALUE 
NOMINVALUE NONE NOORDER NOPARALLEL NORESETLOGS
NORMAL NOSORT NOT NOWAIT NULL NUMBER_BASE
NUMERIC NAME NAN NATIONAL NATIVE OCIROWID OF
OFF OFFLINE OLD ON ONLINE ONLY OPAQUE OPEN
OPERATOR OPTIMAL OPTION OR ORDER ORGANIZATION
OTHERS OUT OUTER OWN OBJECT OVERLAPS OCICOLL
OCIDATETIME OCIDATE OCIDURATION OCIINTERVAL
OCILOBLOCATOR OCINUMBER OCIRAW OCIREFCURSOR 
OCIREF OCISTRING OCITYPE ORACLE ORADATA 
OVERRIDING ORLANY ORLVARY OUTLINE COST 
PACKAGE PARALLEL PARTITION PASCAL PCTFREE 
