ABORT ACCESS ADD ADMIN AFTER ALL ALLOCATE ALTER
ANALYZE AND ANY ARCHIVE ARCHIVELOG ARRAY 
ARRAYLEN AS ASC ASSERT ASSIGN AT AUDIT AUTHID
AUTHORIZATION AVG AGGREGATE AGENT ASSOCIATE
ATTRIBUTE BACKUP BASE_TABLE BECOME BEFORE BEGIN
BETWEEN BLOCK BODY BULK BY BOTH BYTE BFILE_BASE
BINARY BLOB_BASE BOUND CACHE CANCEL CASCADE
CASE CHANGE CHAR_BASE CHARACTER CHECK 
CHECKPOINT CLOSE CLUSTER CLUSTERS COALESCE
COBOL COLAUTH COLLECT COLUMN COLUMNS COMMENT
COMMIT COMMITTED COMPILE COMPRESS CONNECT
CONSTANT CONSTRAINT CONSTRAINTS CONTENTS
CONTINUE CONTROLFILE CONTEXT COUNT CRASH
CREATE CROSS CURRENT CURRVAL CURSOR CYCLE
CALL CALLING CONVERT CHARSETFORM CHARSETID 
