SPACE SQL SQLCODE SQLERRM SQLERROR START
STATEMENT STATEMENT_ID STATISTICS STDDEV
STOP STORAGE SUBPARTITION SUBTYPE SUCCESSFUL 
SUM SWITCH SYNONYM SYSDATE SYSTEM SAMPLE
SUBMULTISET SUBSTITUTABLE SELF STANDARD 
STRING SB1 SB2 SB4 SERIALIZABLE SHORT SIZE_T
SQLDATA SQLNAME SQLSTATE STATIC STORED STRUCT
SPARSE STYLE SPFILE TABAUTH TABLE TABLES
TABLESPACE TASK TEMPORARY TERMINATE THEN 
THREAD TIME TIMEZONE_ABBR TIMEZONE_HOUR
TIMEZONE_MINUTE TIMEZONE_REGION TO TRACING
TRANSACTION TRIGGER TRIGGERS TRUE TRUNCATE 
TYPE THE TRAILING TRANSACTIONAL TRUSTED TDO
UID UNDER UNION UNIQUE UNLIMITED 
UNRECOVERABLE UNTIL UPDATE USE USER USING 
