UB1 UB2 UB4 UNSIGNED UNTRUSTED VALIST VOID
VALIDATE VALUES VARIANCE VIEW VIEWS VARRAY
VARYING VARIABLE WHEN WHENEVER WHERE WHILE
WITH WORK WRITE WRAPPED XOR YEAR ZONE
MINVALUE MLSLABEL MOD MODE MODIFY MODULE 
