PCTINCREASE PCTREE PCTUSED PLAN PLI POSITIVE
POSITIVEN PRAGMA PRECISION PRIMARY PRIOR
PRIVATE PRIVILEGES PROCEDURE PROFILE PUBLIC
PARAMETER PARAMETERS PIPE PIPELINED 
PARALLEL_ENABLE PFILE POINT PURGE QUOTA
RAISE RANGE READ REAL RECORD RECOVER
REFERENCES REFERENCING RELEASE RENAME 
REPLACE RESETLOGS RESOURCE RESTRICTED 
RETURN REUSE REVERSE REVOKE RIGHT ROLE ROLES
ROLLBACK ROW ROWLABEL ROWNUM ROWS ROWTYPE
RUN REF REFERENCE RETURNING REMAINDER RESULT
RESULT_CACHE RELIES_ON RESTORE SAVEPOINT 
SCHEMA SCN SECOND SECTION SEGMENT SELECT
SEPARATE SEPERATE SEQUENCE SESSION SET SHARE
SHARED SIZE SMALLINT SNAPSHOT SOME SORT 
