BFILE BINARY_DOUBLE BINARY_FLOAT BINARY_INTEGER
BLOB BOOLEAN CHAR CLOB DATE DECIMAL DOUBLE
FLOAT INTEGER INTERVAL INTERVAL DAY TO SECOND
INTERVAL YEAR TO MONTH LONG LONG RAW NCHAR
NCLOB NUMBER NVARCHAR NVARCHAR2 ROWID
PLS_INTEGER RAW REF TIMESTAMP TIMESTAMP 
WITH LOCAL TIME ZONE TIMESTAMP WITH TIME ZONE
UROWID VARCHAR VARCHAR2 XML 
