@ ACC ACCEPT A APPEND ARCHIVE ATTR ATTRIBUTE
BRE BREAK BTI BTITLE C CHANGE CL CLEAR COL
COLUMN COMP COMPUTE CONN CONNECT COPY DEF
DEFINE DEL DESC DESCRIBE DISC DISCONNECT ED
EDIT EXEC EXECUTE EXIT GET HELP HO HOST I 
INPUT L LIST PASSW PASSWORD PAU PAUSE PRI
PRINT PRO PROMPT QUIT RECOVER REM REMARK REPF
REPFOOTER REPH REPHEADER R RUN SAV SAVE SET
SHO SHOW SHUTDOWN SPO SPOOL STA START STARTUP
STORE TIMI TIMING TTI TTITLE UNDEF UNDEFINE 
VAR VARIABLE WHENEVER XQUERY 
